### ISSUE TITLE
Visualizing annotations

### ISSUE THREAD

**Issue by atabakd** [everymind/CuttleShuttle-Analysis#1]
I have added a small [notebook](https://github.com/everymind/CuttleShuttle-Analysis/blob/master/Workflows/detection/annotations-to-boundingbox.ipynb) to visualize the annotations, but they seem wrong :disappointed: 
Maybe @glopesdev or @taunsquared can modify it so that it displays the locations correctly?

**Comment by glopesdev** [comment]
It seems like the rescaling of the annotations is not correct. Have you compared the range of the converted output values to the image size? Just to make sure that the order of dimensions is correct (also the Y-axis is probably flipped).

**Comment by atabakd** [comment]
Yes, it is possible that the Y-axis is flipped, but it does not resolve the issue and I do not feel comfortable with forcing the values to be between -1 and 1. This causes the fish to go outside the cage. The min x and y values are around -0.2 or -0.3 **.** 
I tried reading the workflow but unfortunately, I couldn't run it on my computer

**Comment by taunsquared** [comment]
What do you want to read from the workflow?

**Comment by atabakd** [comment]
I want to know how to map the coordinates you have in the csv file to the images.
If you look at the notebook, by just scaling them to the image size, I don't get a correct rectangle on top of the fish.
:point_right: I was trying to see from the workflow how you normalize your mouse clicks with respect to the image but I couldn't run the workflow.

**Comment by taunsquared** [comment]
so the coordinate frame is -1,-1 (bottom left corner) and 1,1 (top right corner). 

can you check your plotting code, pass it the coordinate (0,0), and what do you get? (0,0) should appear directly in the middle.

**Comment by taunsquared** [comment]
basically, can you test each of the corners?

**Comment by atabakd** [comment]
Thanks @taunsquared and @science-code.
